# Generated by Django 3.1.7 on 2021-04-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='portion_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
