# Generated by Django 3.1.7 on 2021-04-25 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_booking_restaurant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_req',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(2)]),
        ),
    ]
