# Generated by Django 3.1.7 on 2021-04-25 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0005_auto_20210425_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='booked',
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(2)]),
        ),
    ]
