# Generated by Django 3.1.7 on 2021-05-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0006_auto_20210425_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_booked',
            new_name='dt_booking_created',
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
