# Generated by Django 3.1.7 on 2021-05-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0007_auto_20210503_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Served', 'Served')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('Entree', 'Entree'), ('Salads', 'Salads'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], max_length=200, null=True),
        ),
    ]
