# Generated by Django 3.1.7 on 2021-05-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0011_category_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_item',
            new_name='item',
        ),
    ]
