# Generated by Django 3.1.7 on 2021-05-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0012_auto_20210503_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ManyToManyField(to='restaurantApp.MenuItem'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
