# Generated by Django 3.1.7 on 2021-07-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0021_auto_20210703_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dt_booking_created',
        ),
    ]
