# Generated by Django 3.1.7 on 2021-07-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0022_remove_booking_dt_booking_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
    ]
