# Generated by Django 3.1.7 on 2021-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0023_remove_booking_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
