# Generated by Django 3.1.7 on 2021-07-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0027_booking_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
