# Generated by Django 3.1.7 on 2021-07-14 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0028_booking_booking_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantApp.booking'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Served', 'Served'), ('Ready for Pickup', 'Ready for Pickup')], max_length=200, null=True),
        ),
    ]
