# Generated by Django 3.1.7 on 2021-07-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0029_auto_20210714_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
